package arm64

// entrypoint enters the machine code generated by this backend which begins with the preamble generated by functionABI.EmitGoEntryPreamble below.
// This implements wazevo.entrypoint, and see the comments there for detail.
func entrypoint(preambleExecutable, functionExecutable *byte, executionContextPtr uintptr, moduleContextPtr *byte, paramResultPtr *uint64, goAllocatedStackSlicePtr uintptr)

// afterGoFunctionCallEntrypoint enters the machine code after growing the stack.
// This implements wazevo.afterGoFunctionCallEntrypoint, and see the comments there for detail.
func afterGoFunctionCallEntrypoint(executable *byte, executionContextPtr uintptr, stackPointer, framePointer uintptr)

// afterThrowTransferEntrypoint is like afterGoFunctionCallEntrypoint, except
// it additionally restores the callee-saved registers from
// wazevo.executionContext.savedRegisters (inlined -- see the .s file; the
// restoreFn blob from Machine.CompileThrowTransferRegisterRestore is accepted
// but unused on arm64) before jumping to targetPC. This implements
// wazevo.afterThrowTransferEntrypoint -- see the comments there and on
// (*callEngine).handleThrow for why a throw-time control transfer needs this
// and afterGoFunctionCallEntrypoint does not: the latter resumes *inside* the
// enter trampoline's own register-restore tail (which hands callee-saved
// registers back before returning to the enter-continuation), whereas a
// throw resumes the catching frame at that enter-continuation directly,
// bypassing that tail entirely.
func afterThrowTransferEntrypoint(restoreFn *byte, executionContextPtr uintptr, stackPointer, targetPC uintptr)
