// Package spectest runs the WebAssembly 3.0 core specification suite with all eight of the proposals
// that version folded in enabled at once.
//
// The per-proposal suites next to this one each run one proposal's own branch of the core suite, with
// only that proposal enabled. That is what proves a proposal works on its own, and it is the only way
// to catch a feature that has quietly become mandatory. It is not enough on its own: those branches
// forked at different times and each carries the encodings of its own moment, so between them no file
// is ever decoded with the whole of 3.0 turned on.
//
// This suite is the other half. It is a single corpus, at the encodings 3.0 actually shipped, run with
// api.CoreFeaturesV3.
//
// Its cases are not committed. They are generated by `make build.spectest.v3` from the ../testsuite
// submodule, which pins WebAssembly/testsuite -- upstream is tracked as upstream, and refreshing it is
// a submodule bump rather than several thousand files of derived output in a diff.
package spectest

import (
	"context"
	"os"
	"testing"

	"github.com/samyfodil/wazy"
	"github.com/samyfodil/wazy/api"
	"github.com/samyfodil/wazy/internal/integration_test/spectest"
	"github.com/samyfodil/wazy/internal/platform"
)

// testcases reads the generated cases from disk. They are derived, so they are not in the tree.
func testcases(t *testing.T) *os.Root {
	root, err := os.OpenRoot(".")
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { root.Close() })
	if _, err := root.Stat("testdata"); err != nil {
		t.Skipf("no cases: run `make build.spectest.v3` to generate them from the testsuite submodule (%v)", err)
	}
	return root
}

func TestCompiler(t *testing.T) {
	if !platform.CompilerSupported() {
		t.Skip()
	}
	spectest.Run(t, testcases(t).FS(), context.Background(),
		wazy.NewRuntimeConfigCompiler().WithCoreFeatures(api.CoreFeaturesV3), spectest.WithMemory64HostModule())
}

func TestInterpreter(t *testing.T) {
	spectest.Run(t, testcases(t).FS(), context.Background(),
		wazy.NewRuntimeConfigInterpreter().WithCoreFeatures(api.CoreFeaturesV3), spectest.WithMemory64HostModule())
}
