package riscv64

// entrypoint enters the machine code generated by this backend, which begins
// with the preamble CompileEntryPreamble produces. This implements
// native.entrypoint; see the comments there for detail.
func entrypoint(preambleExecutable, functionExecutable *byte, executionContextPtr uintptr, moduleContextPtr *byte, paramResultPtr *uint64, goAllocatedStackSlicePtr uintptr)

// afterGoFunctionCallEntrypoint re-enters the machine code after a Go call,
// e.g. once the stack has been grown. This implements
// native.afterGoFunctionCallEntrypoint.
func afterGoFunctionCallEntrypoint(executable *byte, executionContextPtr uintptr, stackPointer, framePointer uintptr)

// afterThrowTransferEntrypoint is afterGoFunctionCallEntrypoint plus a restore
// of the callee-saved registers from native.executionContext.savedRegisters
// (inlined -- see the .s file; the blob from
// Machine.CompileThrowTransferRegisterRestore is accepted but unused here, as
// on arm64) before jumping to targetPC. This implements
// native.afterThrowTransferEntrypoint -- see the comments there and on
// (*callEngine).handleThrow for why a throw-time transfer needs this and an
// ordinary Go-call return does not: the latter resumes inside the enter
// trampoline's own register-restore tail, whereas a throw resumes the catching
// frame at its enter-continuation and bypasses that tail entirely.
func afterThrowTransferEntrypoint(restoreFn *byte, executionContextPtr uintptr, stackPointer, targetPC uintptr)
