package amd64

// entrypoint enters the machine code generated by this backend which begins with the preamble generated by functionABI.EmitGoEntryPreamble below.
// This implements native.entrypoint, and see the comments there for detail.
func entrypoint(preambleExecutable, functionExecutable *byte, executionContextPtr uintptr, moduleContextPtr *byte, paramResultPtr *uint64, goAllocatedStackSlicePtr uintptr)

// afterGoFunctionCallEntrypoint enters the machine code after growing the stack.
// This implements native.afterGoFunctionCallEntrypoint, and see the comments there for detail.
func afterGoFunctionCallEntrypoint(executable *byte, executionContextPtr uintptr, stackPointer, framePointer uintptr)

// afterThrowTransferEntrypoint is like afterGoFunctionCallEntrypoint, except
// it additionally restores the callee-saved registers from
// native.executionContext.savedRegisters (via restoreFn, a tiny blob
// produced by Machine.CompileThrowTransferRegisterRestore) before jumping to
// targetPC. This implements native.afterThrowTransferEntrypoint -- see the
// comments there and on (*callEngine).handleThrow for why a throw-time
// control transfer needs this and afterGoFunctionCallEntrypoint does not.
func afterThrowTransferEntrypoint(restoreFn *byte, executionContextPtr uintptr, stackPointer, framePointer, targetPC uintptr)
