// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

const repo = 'https://github.com/samyfodil/wazy';

export default defineConfig({
  // Keeps the dev overlay out of screenshots and off the page while designing.
  devToolbar: { enabled: false },
  // GitHub Pages project site. Swap both for a custom domain (and add a CNAME).
  site: 'https://samyfodil.github.io',
  base: '/wazy',
  integrations: [
    starlight({
      title: 'wazy',
      description:
        'A WebAssembly runtime written in pure Go: zero dependencies, no CGO, an optimizing amd64/arm64 compiler, the Component Model, WASI 0.2 and the WASI 0.3 async ABI.',
      logo: {
        light: './src/assets/wazy-logo-light.svg',
        dark: './src/assets/wazy-logo-dark.svg',
        replacesTitle: true,
      },
      social: [{ icon: 'github', label: 'GitHub', href: repo }],
      editLink: { baseUrl: `${repo}/edit/main/website/` },
      customCss: [
        '@fontsource-variable/familjen-grotesk',
        '@fontsource/ibm-plex-mono/400.css',
        '@fontsource/ibm-plex-mono/500.css',
        './src/styles/brand.css',
      ],
      lastUpdated: true,
      // Expressive Code is configured in ec.config.mjs.
      sidebar: [
        {
          label: 'Start here',
          items: [
            { slug: 'introduction' },
            { slug: 'getting-started' },
          ],
        },
        {
          label: 'Examples',
          // Autogenerated, not an explicit slug list: pages are ordered by their
          // frontmatter `sidebar.order`, and a page that is missing or still
          // being written does not take the whole site down with it.
          items: [{ autogenerate: { directory: 'examples' } }],
        },
        {
          label: 'Guides',
          items: [
            { slug: 'guides/core-modules' },
            { slug: 'guides/host-functions' },
            { slug: 'guides/components' },
            { slug: 'guides/custom-wit' },
            { slug: 'guides/wasi' },
            { slug: 'guides/async' },
            { slug: 'guides/sandboxing' },
            { slug: 'guides/caching' },
          ],
        },
        {
          label: 'Reference',
          items: [
            { slug: 'reference/cli' },
            { slug: 'reference/platforms' },
            { slug: 'reference/performance' },
            { slug: 'reference/conformance' },
            { slug: 'reference/from-wazero' },
          ],
        },
        {
          label: 'API reference',
          items: [
            { label: 'pkg.go.dev', link: 'https://pkg.go.dev/github.com/samyfodil/wazy', attrs: { target: '_blank' } },
          ],
        },
      ],
    }),
  ],
});
