[package]
name = "greet"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
wit-bindgen-rt = { version = "0.44.0", features = ["bitflags"] }

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = "s"
strip = true
lto = true

[package.metadata.component]
package = "wazy:examples"

[package.metadata.component.target]
path = "greet.wit"
world = "greeter"
