package api_test

import (
	"context"
	_ "embed"
	"fmt"
	"log"

	"github.com/samyfodil/wazy"
	"github.com/samyfodil/wazy/api"
)

// fac.wasm was generated by the following:
//
//	wat2wasm --enable-tail-call fac.wat
//
//go:embed testdata/fac.wasm
var tailcallWasm []byte

// This shows how to use a WebAssembly module compiled with the tail-call feature.
func ExampleCoreFeatureTailCall() {
	// Use a default context
	ctx := context.Background()

	// TailCall support must be enabled explicitly in addition to standard V2 features.
	cfg := wazy.NewRuntimeConfig().WithCoreFeatures(api.CoreFeaturesV2 | api.CoreFeatureTailCall)

	r := wazy.NewRuntimeWithConfig(ctx, cfg)
	defer r.Close(ctx)

	wasmCompiled, err := r.CompileModule(ctx, tailcallWasm)
	if err != nil {
		log.Panicln(err)
	}

	mod, err := r.InstantiateModule(ctx, wasmCompiled, wazy.NewModuleConfig().WithStartFunctions("_initialize"))
	if err != nil {
		log.Panicln(err)
	}

	res, err := mod.ExportedFunction("fac-acc").Call(ctx, 10, 1)
	if err != nil {
		log.Panicln(err)
	}
	fmt.Println(res[0])
	// Output: 3628800
}
